export type Film = {
  imageSrc: string,
  title: string,
  genre: string,
  release: string,
  trailerSrc: string,
  isActive: boolean,
  value: string,
  starring: string,
  director: string,
  description: string,
  id: number,
}

export const films: Film[] = [
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 0,
  },
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 1,
  },
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 2,
  },
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 3,
  },
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 4,
  },
  {
    imageSrc: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Drama',
    release: '2012',
    trailerSrc: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    isActive: false,
    value: '1:30:29',
    starring: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe and other',
    director: 'Bill Murray',
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.',
    id: 5,
  },
];
